# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-test-deploy:
    docker:
      - image: circleci/openjdk:11-jdk-node-browsers-legacy
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      # Then run your tests!
      - run:
          name: Test
          command: mvn test
      - restore_cache:
           key: v3-immo-{{ checksum ".circleci/install-and-activate-google-cloud-sdk.sh" }}
      - run: mvn dependency:go-offline
      - run: /bin/bash .circleci/install-and-activate-google-cloud-sdk.sh
      - run: mvn appengine:deploy
      - save_cache:
          key: v3-immo-{{ checksum ".circleci/install-and-activate-google-cloud-sdk.sh" }}
          paths:
            - ~/google-cloud-sdk
            - ~/.m2

workflows:
  sample:
    jobs:
      - build-test-deploy
